### ISSUE TITLE
[CI/CD] - Add Lint support

### ISSUE THREAD

**Issue by burntcarrot** [k3ai/k3ai#26]
On running `golangci-lint` on my local machine, I was able to find 40+ linting issues. 

10 of them were `deadcode` issues, so it can be ignored as they're a part of adding code for future releases.

The rest are ineffectual assignments and skipped error checks. We can log the error message for the skipped error checks; it would help us more in debugging.

I know this sounds like a minor issue, but with more code coming in the subsequent releases, addressing this earlier can help us save a lot of time maintaining good quality code.

**Suggested Fix:**
Add `golangci-lint` action as workflow to check linting issues. We can add a rule for excluding `deadcode` issues for now.

**Comment by burntcarrot** [comment]
If you want me to fix this, can I open a PR?

**Comment by alefesta** [comment]
yes please!!!!

**Comment by burntcarrot** [comment]
Related PR: #27.
