### ISSUE TITLE
[Feature] - Implement a system domain to automatically bind the plugins

### ISSUE THREAD

**Issue by alefesta** [k3ai/k3ai#3]
K3ai should implement an automatice system domain (i.e: sslip.io or nip.io) so that any plugin installed could be exposed with the standard: 
`<plugin-name>.<clusterIP>.nip.io`
This way we may use the same IP in cases like:

- WSL
- Laptops

**Comment by alefesta** [comment]
We need to evaluate a solution for https://github.com/k3ai/k3ai/issues/24 for all those cases where we need to use port-forwarding instead of the nodePort.

**Comment by burntcarrot** [comment]
Related discussion from #24:

> WSL2 uses dynamic IP that does not goes along with K8s very well. This is not up to K3ai but to the K8s providers. Docker addresses this natively with their proxy but..

Yes, I know the pain working with dynamic IPs, here's the [related issue](https://github.com/microsoft/WSL/issues/4210) suggesting some workarounds for this. I also found [a workaround for setting static IPs](https://github.com/ocroz/wsl2-boot), but these require administrator access, which some users might not be ready to give.

> some like KinD project use extra-ports mapping but the limitation there is that the pod port and the nodePort have to be the same.

This is a known issue. Maybe we can address these issues in the docs itself? (probably in a FAQ, WSL2 has a lot of issues)

> I should hack too many things that would become un-mantainable on the long run.. so port-forward may be a solution, something on the line k3ai plugin -n mlflow -port-forward but it would result in something like a terminal where you cannot operate otherwise it would stop the port-forward. Still would means the user would have to open another terminal to run any other command...

Non-blocking or detachable commands are good. Adding the `-port-forward` flag should not have any effect on terminal usability, unless it is considered or advertised as a "terminal-blocking" command.

> I was thinking maybe get a complementary app to expose ports as port-forward ? Something like k3ai-expose that is invocated when the plugin is deployed and adds a port-forward for the service "on-demand"?

`k3ai-expose` looks good, maybe we can run it as a bash script running the prebuilt binaries?

Thanks for creating k3ai! I'm not much into ML deployments, but I was looking for a project which I can contribute to! 😀 (through bug reports or even code contributions)

**Comment by alefesta** [comment]
Closing since is a duplicate of #28
