### ISSUE TITLE
[BUG] k3ai up yields version `GLIBC_2.28' not found error

### ISSUE THREAD

**Issue by htahir1** [k3ai/k3ai#41]
**Describe the bug**
After following the installation instructions, the following error is reported:

`k3ai: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by k3ai)`

**To Reproduce**
1. curl -LO https://get.k3ai.in | sh -
2. k3ai up

**Expected behavior**
It should have spun up the cluster!

OS: Ubuntu 18.04

**Comment by alefesta** [comment]
Implemented in v1.0.1 - The new installer should work automatically.

**Comment by daniel-vera-g** [comment]
> Implemented in v1.0.1 - The new installer should work automatically.

Should this issue be fixed in v1.0.1 @alefesta  ? Tested it with this release and Ubuntu 18.04, but still got the same error.

**Comment by alefesta** [comment]
It should I've compiled this version against a 18.04 Ubuntu box.. next week I'll take a look again, in the meantime I'll reopen this bug.
Thanks for reporting and happy new year!

**Comment by alefesta** [comment]
@daniel-vera-g this should be fixed now, Just re-download the k3ai binary and overwrite the older one.
```
 curl -sfL https://get.k3ai.in | sh -
```
should do everything for you automatically

**Comment by alefesta** [comment]
I'll leave this open for a while just to double-check this is fixed correctly.

**Comment by daniel-vera-g** [comment]
> I'll leave this open for a while just to double-check this is fixed correctly.

Thanks! Works as expected now 👍
