### ISSUE TITLE
[BUG] - Kubeflow Pipelines Quickstart Repository Missing

### ISSUE THREAD

**Issue by harshitmahapatra** [k3ai/k3ai#52]
**Describe the bug**
I was trying to follow the kubeflow pipelines tutorial as described in the k3ai [website](https://k3ai.github.io/docs/tutorials/kubeflow).
It seems the final step of running the pipeline fails because the quickstart repository for kubeflow pipelines does not exist.
 
**To Reproduce**
1. `k3ai up`
2. `k3ai cluster deploy -t k3s -n myk3scluster`
3. `k3ai plugin deploy -n kf-pa -t myk3scluster`
4. `k3ai run -s https://github.com/k3ai/quickstart/kfp -b kfp -e condition.py -t mycluster`

**Expected behavior**
Pipeline to run successfully.

**Actual behavior**
Pipeline run fails.

**Comment by harshitmahapatra** [comment]
Awesome library by the way.
If you could use some helping hands, I am more than happy to help :)

**Comment by alefesta** [comment]
Hey @harshitmahapatra  first thanks for opening up the issue, second definitely more than welcome to help here...
If there is anything you would like to start working feel free to pick it up or make a proposal.. or simply if you got an example to share we may add to the docs that would be awesome!

On your bug, could give me more details? 
Pipeline run fails means it throw an error when you execute `k3ai run` or in Kubeflow directly?

These days I'm a bit busy with some other things so I'll be able to restart working on K3ai in a couple of weeks btw.

**Comment by harshitmahapatra** [comment]
@alefesta 
Thanks I will take a lot at issues :)

Regarding the issue, my guess is kubeflow compile fails because there is nothing to compile.
So it is less of a bug and more of a missing quickstart example issue. 

**Command**
`k3ai run --source https://github.com/k3ai/quickstart/kfp -b kfp -e condition.py -t aicluster`

**Output**
```
🧪	Initializing code...
deployment.apps/k3ai-executor unchanged

 🧪	Working, please wait... 
2022/03/17 07:20:17 2022/03/17 07:20:17 Traceback (most recent call last):
2022/03/17 07:20:17 2022/03/17 07:20:17   File "/opt/conda/bin/dsl-compile", line 8, in <module>
2022/03/17 07:20:17 2022/03/17 07:20:17     sys.exit(main())
2022/03/17 07:20:17 2022/03/17 07:20:17   File "/opt/conda/lib/python3.9/site-packages/kfp/compiler/main.py", line 133, in main
2022/03/17 07:20:17 2022/03/17 07:20:17     compile_pyfile(
2022/03/17 07:20:17 2022/03/17 07:20:17   File "/opt/conda/lib/python3.9/site-packages/kfp/compiler/main.py", line 108, in compile_pyfile
2022/03/17 07:20:17 2022/03/17 07:20:17     __import__(os.path.splitext(filename)[0])
2022/03/17 07:20:17 2022/03/17 07:20:17 ModuleNotFoundError: No module named 'condition'
2022/03/17 07:20:17 2022/03/17 07:20:17 ..Preparing pipeline...
2022/03/17 07:20:20 2022/03/17 07:20:20 ..Pushing pipeline...
2022/03/17 07:20:24 2022/03/17 07:20:24 Usage: kfp run submit [OPTIONS] [ARGS]...
2022/03/17 07:20:24 2022/03/17 07:20:24 Try 'kfp run submit --help' for help.
2022/03/17 07:20:24 2022/03/17 07:20:24 
2022/03/17 07:20:24 2022/03/17 07:20:24 Error: Invalid value for '-f' / '--package-file': File '/tmp/git/quickstart/kfp/1647501616807838211.tar.gz' does not exist.
2022/03/17 07:20:24 
🧪      Completing execution... 100% |████████████████████████████████████████|   3s:0s]
✔️	Done. You may check your code directly on the backend platform.
```

**Issue**
There is no run in the kubeflow pipelines.

**Comment by alefesta** [comment]
🤦🤦🤦 So sorry about this...it's a **BIG** typo in the documentation...

The right command is (in your case):
`k3ai run -s https://github.com/k3ai/sample/kfp/ -b kfp -e condition.py -t aicluster`
while you are executing (as per docs)_
`k3ai run --source https://github.com/k3ai/quickstart/kfp -b kfp -e condition.py -t aicluster`

notice as I'm running against `sample` and **NOT** `quickstart`
Was my fault in docs!

Going to open an issue on this..fancy a contribution to fix it?
😄

**Comment by harshitmahapatra** [comment]
> 
@alefesta 
Yes of course :) 
If you create an issue and assign to me, I will do the needed changes.
