### ISSUE TITLE
[BUG] - runtime error with index out of range when running quickstart

### ISSUE THREAD

**Issue by jeinstei** [k3ai/k3ai#53]
**Describe the bug**

**To Reproduce**
1. Follow quickstart steps:
```
k3ai up
k3ai cluster deploy -t k3s -n mycluster
k3ai plugin deploy -n mlflow -t mycluster
```

2. Try running quickstart: `$ k3ai run -s https://github.com/k3ai/quickstart -b mlflow`
3. Receive error:
```
🧪	Initializing code...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/k3ai/pkg/runner.Loader({0x7fff7fe7bb4e, 0x22}, {0x0, 0x0}, {0x7fff7fe7bb74, 0x6}, {0x0, 0x0}, {0x0, 0x0})
	/home/joshec/git/k3ai/pkg/runner/run.go:78 +0x10f6
github.com/k3ai/cmd.runCommand.func1(0xc000403680, {0xc0003d57c0, 0x0, 0x4})
	/home/joshec/git/k3ai/cmd/run.go:71 +0x58b
github.com/spf13/cobra.(*Command).execute(0xc000403680, {0xc0003d5780, 0x4, 0x4})
	/home/joshec/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2254960)
	/home/joshec/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/joshec/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/k3ai/cmd.Execute(...)
	/home/joshec/git/k3ai/cmd/root.go:34
main.main()
	/home/joshec/git/k3ai/main.go:10 +0x25
```

**Expected behavior**

A successful run with proper artifact storage and tracking URI settings

**Screenshots**

**Comment by alefesta** [comment]
Hey @jeinstei thanks for the issue..just to confirm did you try the command as:
`k3ai run -s https://github.com/k3ai/quickstart -b mlflow`

or as 

`k3ai run -s https://github.com/k3ai/quickstart -b mlflow -t mycluster`

This is just because the first case would explain the error and I've just noticed in the docs I indeed forgot the "target"(sorry about that)

**Comment by jeinstei** [comment]
That explains both the error and such. Maybe more of a feature request for descriptive errors then :D

That looks to have resolved this bug. I'm getting now getting a `Unable to list artifacts stored under <code>{artifactUri}</code> for the current run.` error in MLflow, but I'm thinking that's a plugin issue more.

**Comment by alefesta** [comment]
Yeah my actual docs are horrible but too many things to do and am alone :) but feature requests are always SUPER welcome!!!
